spring:
  application:
    name: resource-booking-system

  datasource:
    url: jdbc:postgresql://localhost:5432/booking_db
    username: postgres
    password: 2003
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080

jwt:
  secret: 289i9vsvkjsnkl94y827439jfw894yru9fe4hfnwr8y3w8r
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs